### ISSUE TITLE
O caminho "auth/login" está como GET

### ISSUE THREAD

**Issue by SamuelLimaCap** [Biblioteca-de-Bolso/backend#11]
O email e a senha está indo diretamente como parâmetro no LINK no caminho "auth/login

**Comment by SamuelLimaCap** [comment]
Preciso que seja post porque a lib do android nao aceita @ GET com bodyRequest. 

![image](https://user-images.githubusercontent.com/67354841/154890248-e4bf7e08-05eb-4701-ace5-5c1031a69a5c.png)

Só consigo caso eu faça com annotation de @ HTTP , mas pra isso eu preciso instanciar a classe de API toda vez que for mandar um request

**Comment by rhenandias** [comment]
Vou providenciar uma branch com a correção.

Semanticamente é mais correto mesmo que essa rota seja do tipo POST, as informações são confidenciais e devem ser enviadas no mesmo pacote que a requisição e não na URL.
