### ISSUE TITLE
Problema na petição para pedir a senha

### ISSUE THREAD

**Issue by SamuelLimaCap** [Biblioteca-de-Bolso/backend#122]
![Screenshot_20221013-014155_Gmail](https://user-images.githubusercontent.com/67354841/195503426-7d06aab8-1928-46f8-80c5-21120964d7da.jpg)
![Screenshot_20221013-013910_Gmail](https://user-images.githubusercontent.com/67354841/195503429-c2519f54-33af-4dcc-86b5-a66571700a87.jpg)

O link para alterar a senha nao chega como o link que combinamos. O que está acontecendo:

Link manda pro server do sendgrid -》 celular abre o browser -》 acessa o link do sendgrid -》 sendgrid redireciona pro link que combinamos

O link final nao pode ser algo que o sendgrid redireciona, senao ele abre o browser. Pro link que combinamos funcionar, ele nao pode, em hipotese alguma, abrir o browser

Assim ele nao abre o browser:

![Screenshot_20221013-014137_Gmail](https://user-images.githubusercontent.com/67354841/195503865-d9900841-7005-46e2-8f5c-a91eef87e0d4.jpg)

![Screenshot_20221013-014708_Gmail](https://user-images.githubusercontent.com/67354841/195504006-b0f95817-ae74-4fc6-8f56-bd9e6639ea19.jpg)

**Comment by SamuelLimaCap** [comment]
Te mandei no whatsapp a versão do app que abre esse o link que combinamos. Acho que com isso vai da pra vc ficar testando

**Comment by rhenandias** [comment]
Opa, corrigido

Era uma configuração de tracking automático de links que o SendGrid tem. Não foi alterado nada em código, apenas uma configuração no painel da SendGrid, eu não sabia que ela existia.
