### ISSUE TITLE
Imagens não estão mostrando no android 9.0+

### ISSUE THREAD

**Issue by SamuelLimaCap** [Biblioteca-de-Bolso/backend#67]
![image](https://user-images.githubusercontent.com/67354841/172291904-6b253a25-f263-4279-92b2-16932906149f.png)
O link da imagem está sendo enviado como "http". Por conta da segurança da API 23, requisições HTTP estão bloqueadas

![image](https://user-images.githubusercontent.com/67354841/172292036-1993e26a-20a9-4f9e-8d70-53b8e6c324cd.png)

**Como corrigir**
Mande links com requisições HTTPS

**Comment by rhenandias** [comment]
Corrigido com o PR #68, atualizar se necessário o aplicativo para evitar a substituição para HTTPs.
