### ISSUE TITLE
Documentação diz que rota de refreshToken precisa de accessToken

### ISSUE THREAD

**Issue by SamuelLimaCap** [Biblioteca-de-Bolso/backend#84]
![image](https://user-images.githubusercontent.com/67354841/182037094-08ce4102-3ffb-42ac-888c-d8dbddd6f724.png)

Se isso for verdade então o refreshToken nunca será usado pois o acessToken expirado não deixará a requisição passar

**Comment by rhenandias** [comment]
Esse comportamento não ocorre, não é um bug. No [middleware de autenticação](https://github.com/Biblioteca-de-Bolso/backend/blob/main/app/src/middlewares/auth.js) são descritas duas rotas, uma `protectedRoute` e outra `refreshTokenRoute`.

A primeira é um middleware utilizado em todas as rotas em que é necessário a autenticação, todas as rotas de interação. A segunda é utilizada justamente na rota de refresh token, onde a validação de JWT expirado é permitida.

![image](https://user-images.githubusercontent.com/12837964/182137043-9a952a09-ebb5-40f6-b2be-8ff2898edad9.png)

Foi feito dessa maneira, pois o refresh token não carrega nenhum metadado referente ao utilizador, ele é apenas um hash. O refresh token é armazenado no banco de dados, mas para validar a origem do refresh token é necessário ter os metadados do token que gerou o refresh token.

O refresh token nessa rota não é utilizado para validação de validade, e sim validação de metadados do portador do refresh token.
